config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  has_one_attached :image, dependent: :nullify
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
    @breadcrumb = "BRAND "
  end

  def new
    @breadcrumb = "CREATE NEW BRAND"
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to new
    else
      render "new"
    end
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      redirect_to new
    else
      render "edit"
    end
  end

  def edit
    @breadcrumb = "UPDATE BRAND"
    @brand = Brand.find(params[:id])
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy()
    redirect_to new
  end

  def brand_params
    params.require(:brand).permit(:name, :description, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(params[:brand_id])
  end

  def indexall
    @products = Product.all
    @breadcrumb = "PRODUCTS"
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to new
    else
      render "new"
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to new
    else
      render "edit"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy()
    redirect_to new
  end

  def product_params
    params.require(:product).permit(:name, :description, :brand_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/edit.html.erb
<div class="form-container">
  <div class="title">
    <h1>EDIT BRAND</h1>
  </div>

<%= simple_form_for @brand do |form| %>

  <%= form.error_notification %>

  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.input :image, as: :file %>



  <div class="form-btn-group"> 
  <%= form.button :submit, class: "btn-send" do %>
  
  <% end %>

  <%= link_to url_for(:back), class: "btn-form", :method => "get" do %>
    Back
  <% end %>
</div>
<% end %>

</div>

app/views/brands/index.html.erb
<div class="card-container">
    <%= link_to new_brand_path, class: "button-create" do %>
    CREATE A NEW BRAND
    <% end %>
   
    <% @brands.each do |brand| %>
      <div class="card">
        
          <%= image_tag brand.image, class: "image-brand" rescue image_tag "placeholder.png", class: "image-brand" %>
        
        <h1 class="brand-name">Name <%= brand.name %></h1>
        <p class="brand-description">
        Description 
        <%= brand.description %>
        </p>
        <div class="buttons">
        <a class="show-button button-menu hvr-grow">
        <i class="fa fa-eye" aria-hidden="true"></i>
        </a>
  

          <%= link_to edit_brand_path(brand.id), class: "edit-button button-menu hvr-grow" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
        
       <% end %>
        
        
        

       <%= link_to brand_path(brand), method: :delete, class: "delete-button button-menu hvr-grow" do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
        
       <% end %>
       
        </div>
  
      </div>
    <% end %>
</div>

app/views/brands/new.html.erb
<div class="form-container">
  <div class="content-title">
  </div>

<%= simple_form_for @brand do |form| %>

  <%= form.error_notification %>

  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.input :image, as: :file %>

<div class="form-btn-group"> 
  <%= form.button :submit, class: "btn-send" do %>
  
  <% end %>

  <%= link_to url_for(:back), class: "btn-form", :method => "get" do %>
    Back
  <% end %>
</div>

<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marka ve Ürün Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= stylesheet_link_tag "hover-min" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;700&display=swap" %>
   
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    
    <%= javascript_include_tag "https://kit.fontawesome.com/0588435aa9.js", :defer => "defer" %>
    
  </head>

  <body>
  <div class="container">
  <div class="sidebar">
      <div class="sidebar-container">
      <div class="brand-container">
        <%= link_to brands_path do %>
          <%= image_tag "demo.png", :class => "demo-logo" %>
          <h3 class="sidebar-expanded logo-text">MARKAURUNAPP</h3>
        <% end %>
      </div>
      <ul class="sidebar-item-container">
        <li class="sidebar-item hvr-icon-bob">
        <i class="fas fa-clipboard-list hvr-icon"></i>
        <%= link_to brands_path, :class => "sidebar-expanded" do %>
          
          BRAND
        <% end %>
        </li>
        <li class="sidebar-item hvr-icon-bob">
        <i class="fas fa-box-open hvr-icon"></i>
                  <%= link_to products_path, :class => "sidebar-expanded" do %>
          
          PRODUCTS
        <% end %>
        </li>
        <li class="sidebar-item hvr-icon-bob">
        <i class="fas fa-parachute-box hvr-icon"></i>
          <a class="sidebar-expanded" href="">EXAMPLE</a>
        </li>
      </ul>
      <div class="sidebar-help">
        <i class="fa fa-question"></i>
        <a class="sidebar-expanded" href="">Help Center</a>
      </div>
    </div>
  </div>
  <div class="item-container">
<h1 class="page-title"><%= @breadcrumb %></h1>
<%= yield %>
  </div>
</div>

    
  </body>
</html>

app/views/products/edit.html.erb
<div class="form-container">
  <div class="title">
    <h1>EDIT BRAND</h1>
  </div>

<%= simple_form_for @product do |form| %>

  <%= form.error_notification %>

  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.input :image, as: :file %>



  <div class="form-btn-group"> 
  <%= form.button :submit, class: "btn-send" do %>
  
  <% end %>

  <%= link_to url_for(:back), class: "btn-form", :method => "get" do %>
    Back
  <% end %>
</div>
<% end %>

</div>

app/views/products/index.html.erb
<div class="card-container">
    <%= link_to new_product_path, class: "button-create" do %>
    CREATE A NEW PRODUCT
    <% end %>
    <% @products.each do |product| %>
      <div class="card">
        
          <%= image_tag brand.image, class: "image-brand" rescue image_tag "placeholder.png", class: "image-brand" %>
        
        <h1 class="brand-name">Name <%= product.brand.name %> <%= product.name %></h1>
        <p class="brand-description">
        Description 
        <%= product.description %>
        </p>
        <div class="buttons">
        <a class="show-button button-menu hvr-grow">
        <i class="fa fa-eye" aria-hidden="true"></i>
        </a>
  

          <%= link_to edit_product_path(product.id), class: "edit-button button-menu hvr-grow" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
        
       <% end %>
        
        
        

       <%= link_to product_path(product.id), method: :delete, class: "delete-button button-menu hvr-grow" do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
        
       <% end %>
       
        </div>
  
      </div>
    <% end %>
</div>

app/views/products/new.html.erb
<div class="form-container">
  <div class="content-title">
    <h1>NEW PRODUCT</h1>
  </div>

<%= simple_form_for @product do |form| %>

  <%= form.error_notification %>

  <%= form.input :name %>
  <%= form.input :description %>

  <div class="box">
<label for="brand">Brand</label>
  <%= form.collection_select(:brand_id, Brand.all, :id, :name) %>
  </div>


<div class="form-btn-group"> 
  <%= form.button :submit, class: "btn-send" do %>
  
  <% end %>

  <%= link_to url_for(:back), class: "btn-form", :method => "get" do %>
    Back
  <% end %>
</div>

<% end %>

</div>